config/routes.rb
Rails.application.routes.draw do
  
  resources :products
  resources :shops, only:[:index, :show]
  resources :order_items
  resources :cards, only:[:index, :show]
  
  resources :users, :addresses
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user 
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :order_items 
    before_save :set_subtotal


    def subtotal
        order_items.collect{|order_item| order_item.valid? ? order_item.unit_price.to_i + order_item.quantity.to_i : 0}.sum
    end


   
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
    belongs_to :order
    belongs_to :product

    before_save :set_unit_price
    before_save :set_total

    def unit_price
        if persisted?
            self[:unit_price]
        else
            product.price
        end
    end

    def total
        unit_price.to_i*quantity
    end

    private
    def set_unit_price
        self[:unit_price] = unit_price
    end

    def set_total
        self[:total] = total*quantity
    end
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :order_items
end

app/models/user.rb
class User < ApplicationRecord
  has_many :addresses
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :current_address, only: [:show, :edit, :update, :destroy]
  
  def index
    @addresses = Address.all
  end

  def show
  end

  def new
    @address = Address.new
  end
  
  def create
    @address = Address.create(address_params)

    redirect_to address_path(@address)
  end

  def edit
  end
  
  def update
    @address.update(address_params)

    redirect_to address_path(@address)
  end

  def destroy
    @address.destroy

    redirect_to addresses_path
  end

  private
  def address_params
    params.require(:address).permit(:doorno, :town, :district, :state, :user_id)
  end

  def current_address
    @address = Address.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include ApplicationHelper
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def index
    @order_items = current_order.order_items
  end

end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController


    def create
        @order = current_order
        @order_item = @order.order_items.new(order_params)
        @order.save
        session[:order_id] = @order.id
    end


    private

    def order_params
        params.require(:order_item).permit(:product_id, :quantity)
    end
end
 

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :price, :rating, :imageUrl)
    end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  def index
    @products   = Product.all
  
    @order_item = current_order.order_items.new
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :current_user, only: [:show, :edit, :update, :destroy]
  
  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end
  
  def create
      @user = User.create(user_params)

      redirect_to user_path(@user)
    end

  def edit
  end
  
  def update
      @user.update(user_params)

      redirect_to user_path(@user)
  end
  
  def destroy
      @user.destroy

      redirect_to users_path
    end

    private
    def user_params
      params.require(:user).permit(:name, :mobile, :age)
    end

    def current_user
      @user = User.find(params[:id])
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    
    def current_order
        if !session[:order_id].nil?
            Order.find(session[:order_id])
        else
            Order.new
        end
    end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/addresses/edit.html.erb
<h3>Edit Address</h3>
<%= form_with model: @address do |form| %>
  <p>Door No: <%= form.number_field :doorno %></p>
  <p>Town: <%= form.text_field :town %></p>
  <p>District: <%= form.text_field :district %></p>
  <p>State: <%= form.text_field :state %></p>

  <p>User: <%= form.select :user_id, User.all.map { |user| [ user.to_s, user.id ] } %></p>
  <%= form.submit %>
<% end %>

app/views/addresses/index.html.erb
<div class="background">
    <div class="user-container">
          <h1>List of Addresses</h1>
          <ul><% @addresses.each do |address| %>
            <li>
              <%= link_to address.town, address_path(address) %>
            <% end %></li>
          </ul>
        
          <div><%= link_to 'Create Address', new_address_path %></div>
  
    </div>
  
</div>

app/views/addresses/new.html.erb
<div class="background">
  <div class="user-container">
      <h3>Add Address</h3>
    <%= form_with model: @address do |form| %>
      <p>Door No: <%= form.number_field :doorno %></p>
      <p>Town: <%= form.text_field :town %></p>
      <p>District: <%= form.text_field :district %></p>
      <p>State: <%= form.text_field :state %></p>

      <p>User: <%= form.select :user_id, User.all.map { |user| [ user.name, user.id ] } %></p>
      <%= form.submit %>
    <% end %>


  </div>
</div>

app/views/addresses/show.html.erb
<h1><%= @address.town %></h1>
<%= link_to 'Edit', edit_address_path(@address) %>
<p><b>Door No:</b> <%= @address.doorno %></p>
<p><b>Town:</b> <%= @address.town %></p>
<p><b>District:</b> <%= @address.district %></p>
<p><b>State:</b> <%= @address.state %></p>


<h4>User: <%= link_to @address.user.name, user_path(@address.user) %></h4>

<p><%= link_to 'Delete', @address, method: 'delete', data: { confirm: 'Are you sure?' }%></p>
<p><%= link_to 'Go back to all addresses', addresses_path %></p>

app/views/cards/index.html.erb
<!DOCTYPE html>
<html>

<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous" />
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
        crossorigin="anonymous"></script>
    <link rel="stylesheet" href="styles.css" />
</head>

<body>
<div class="application-container">
<div class="shop-bg-container">
        
<% @order_items.each do |item| %>
  
  
  <div class="cart-shops-container p-3">
  
  <%= image_tag(item.product.imageUrl, :class => "shop-image")%>
    <p class="shop-list font-weight-bold mb-0">name:<%= item.product.name %></p>
    <p class="shop-list mb-0">price:<%= item.product.price %></p>
    <p class="shop-list mb-0">rating:<%= item.product.rating %></p>

    <%= form_for item do |f| %>
        <%= f.hidden_field :product_id, :value => item.product.id %>
        <p class="card-shop-list"><%= f.number_field :quantity, :value => item.quantity.to_i, :class =>"quantity-field" %></p>
        <div class="text-left mt-2">
            <p class="add-cart"><%= f.submit "update cart", :class => "btn btn-primary" %></p>
        </div>
    <% end %>
    <p>subtotal: <%= item.total %></p>
    </div>


<% end %>

</div>

</div>

</body>

</html>

          
            
            
            
  

app/views/layouts/_navbar.html.erb
<!DOCTYPE html>
<html>

<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous" />
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
        crossorigin="anonymous"></script>
    <link rel="stylesheet" href="styles.css" />
</head>

<body>
<nav class="navbar navbar-light bg-primary">
<div class="d-flex flex-row">

    <div class="">
    <a class="navbar-brand"><%= link_to "Home", users_path, :class=>"btn btn-primary"%></a>
    </div>

    <div >
    <a class="navbar-brand"><%= link_to "product", products_path, :class=>"btn btn-primary" %></a>
    </div>
    <div >
    <a class="navbar-brand"><%= link_to "Address", addresses_path, :class=>"btn btn-primary" %></a>
    </div>
    <div >
    <a class="navbar-brand"><%= link_to "Shop", shops_path, :class=>"btn btn-primary" %></a>
    </div>
</div>
  
</nav>


</body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UserAddr</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :rating %>
    <%= form.text_field :rating %>
  </div>

  <div class="field">
    <%= form.label :imageUrl %>
    <%= form.text_field :imageUrl %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Rating</th>
      <th>Imageurl</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.price %></td>
        <td><%= product.rating %></td>
        <td><img src=<%= product.imageUrl %> class="image" alt="Girl in a jacket" width="100px" height="100px"></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @product.rating %>
</p>

<p>

  
  <img src=<%= @product.imageUrl %> alt="Girl in a jacket" width="200" height="200">

</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/shops/index.html.erb
<!DOCTYPE html>
<html>

<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous" />
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
        crossorigin="anonymous"></script>
    <link rel="stylesheet" href="styles.css" />
</head>

<body>
<div class="application-container">
<div class="shop-bg-container">
        
<% @products.each do |product| %>
  
  
  <div class="shops-container p-3">
  
  <%= link_to image_tag(product.imageUrl, :class => "shop-image"),product %>
    <p class="shop-list font-weight-bold mb-0">name:<%= product.name %></p>
    <p class="shop-list mb-0">price:<%= product.price %></p>
    <p class="shop-list mb-0">rating:<%= product.rating %></p>

    <%= form_for @order_item do |p| %>
        <%= p.hidden_field :product_id, :value => product.id %>
        <p class="shop-list">quantity:<%= p.number_field :quantity, :value => 1, :min => 1, :class =>"quantity-field" %></p>
        <div class="text-left mt-2">
            <p class="add-cart"><%= p.submit "Add to cart", :class => "btn btn-primary" %></p>
        </div>
        
    <% end %>
    </div>


<% end %>

</div>
<div class="text-center">
    <%= link_to "Go to cart", cards_path, :class => "btn btn-primary"%>
</div>

</div>

</body>

</html>

          
            
            
            
  

app/views/shops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @product.rating %>
</p>

<p>

  
  <img src=<%= @product.imageUrl %> alt="Girl in a jacket" width="200" height="200">

</p>

<%= link_to 'Back', products_path %>
 

app/views/users/edit.html.erb
<h3>Edit User</h3>
<%= form_with model: @user do |form| %>
  <p>Name: <%= form.text_field :name %></p>
  <p>Mobile: <%= form.number_field :mobile %></p>
  <p>Age: <%= form.number_field :age %></p>
  <%= form.submit %>
<% end %>

app/views/users/index.html.erb
<div class="background">
<h1 class="heading">List of Users</h1>
    <div class="user-container">
        <ul class="list"><% @users.each do |user| %>
          <li>
            <p class="paragraph"><%= link_to user.name, user_path(user), :class=>"para" %></p>
          <% end %></li>
        </ul>

      <div class="create"><%= link_to 'Create User', new_user_path %></div>
    </div>
</div>
  

app/views/users/new.html.erb
<div class="background">
  <div class="user-container">
      <h3>Add User</h3>
      <%= form_with model: @user do |form| %>
        <p>Name: <%= form.text_field :name %></p>
        <p>Mobile: <%= form.number_field :mobile %></p>
        <p>Age: <%= form.number_field :age %></p>
        <%= form.submit %>
      <% end %>
  </div>
  <div>
    <p>Changes</p>
  </div>
</div>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>
<%= link_to 'Edit', edit_user_path(@user) %>
<p><b>Mobile:</b> <%= @user.mobile %></p>
<p><b>Age:</b> <%= @user.age %></p>


<h3>Addresses</h3>
<ul>
  <% @user.addresses.each do |address| %>
  <li><%= link_to address.town, address_path(address) %></li>
  <% end %>
</ul><br>

<p><%= link_to 'Delete', @user, method: 'delete', data: { confirm: 'Are you sure?' }%></p>
<p><%= link_to 'Go back to all users', users_path %></p>